language: python

sudo: false

python:
  - "3.4"
  - "3.5"
  - "3.6"

cache:
    pip: true

before_install:
    - pip install -U pip wheel setuptools
    - pip install codecov

install:
    - pip install -r requirements.txt

script:
    - coverage run setup.py test

after_success:
    - codecov
